name: 'twitch_bi'
version: '1.0.0'

profile: 'twitch_bi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  twitch_bi:
    staging:
      +materialized: view
      +schema: stg
      stg_streams:
        post-hook: "{{ drop_tables(schema='main', table_name_ilike='dbt_tmp') }}"